apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  namespace: koneksyonapi
  name: koneksyon-api-ingressroute
  annotations:
    external-dns.alpha.kubernetes.io/target: traefik.plagueworks.org
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    external-dns.alpha.kubernetes.io/cloudflare-comment: "Koneksyon API managed by ExternalDns in oke-poseidon-apps"
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`koneksyon-api.plagueworks.org`) 
      services:
        - name: koneksyon-api
          port: 80
  tls:
    certResolver: le